app/models.py
from app import db


class Record(db.Model):
    __tablename__ = 'records'

    uuid = db.Column(db.Text, primary_key=True)
    record_category_uuid = db.Column(db.Integer, db.ForeignKey('record_categories.uuid'), nullable=False)
    date = db.Column(db.Date, nullable=False)
    time = db.Column(db.Time, nullable=True)
    kind = db.Column(db.Text, nullable=False)
    value = db.Column(db.Integer, nullable=False)
    change_id = db.Column(db.Integer, nullable=False)
    deleted = db.Column(db.Boolean, nullable=False, default=False)


class RecordCategory(db.Model):
    __tablename__ = 'record_categories'

    uuid = db.Column(db.Text, primary_key=True)
    record_type_id = db.Column(db.Integer, db.ForeignKey('record_types.id'), nullable=False)
    name = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, nullable=False)
    records = db.relationship('Record', backref='record_category', lazy='dynamic')


class RecordType(db.Model):
    __tablename__ = 'record_types'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text, nullable=False, unique=True)
    record_categories = db.relationship('RecordCategory', backref='record_type', lazy='dynamic')


class DaySum:
    def __init__(self, row):
        self.date = row[0]
        self.sum = row[1]


class MonthSum:
    def __init__(self, row):
        self.year = int(row[0])
        self.month = int(row[1])
        self.sum = row[2]

app/main/forms.py
import datetime
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, SelectField
from wtforms.validators import Length, DataRequired, ValidationError, Optional

from app.form import DateFieldWidget, IntegerFieldWidget, TimeFieldWidget
from app.models import RecordType


class AddRecordForm(FlaskForm):
    type = SelectField('тип', coerce=int)
    date = DateFieldWidget('дата', validators=[DataRequired()], default=datetime.date.today)
    time = TimeFieldWidget('время', validators=[Optional()], default=datetime.datetime.now)
    kind = StringField('вид', validators=[Length(1, 64)])
    value = IntegerFieldWidget('сумма', validators=[DataRequired()])
    submit = SubmitField('сохранить')

    def __init__(self, *args, **kwargs):
        super(AddRecordForm, self).__init__(*args, *kwargs)
        self.type.choices = [(t.id, t.name) for t in RecordType.query.all()]

    def validate_value(self, field):
        if field.data <= 0:
            raise ValidationError('value <= 0')
        if field.data > 100000:
            raise ValidationError('value > 100.000')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy

from config import config

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)

    from app.main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
import datetime

from dateutil.relativedelta import relativedelta
from flask import render_template, request, abort

from sqlalchemy import func

from app import db
from app.main import main
from app.models import Record, RecordCategory, RecordType
from app.utils import get_sums_by_days_spends, get_sums_by_months_spends, get_years, get_sums_by_categories_month
from config import Config


@main.route('/')
def index():
    start_date = datetime.date.today()
    start_date = start_date.replace(day=1)
    start_date = start_date + relativedelta(months=-1)

    records = Record.query \
        .join(RecordCategory, Record.record_category_uuid == RecordCategory.uuid) \
        .filter(RecordCategory.user_id == Config.records_user_id(), Record.date >= start_date,
                Record.deleted == False) \
        .order_by(Record.date.desc(), Record.time.desc().nullslast(), RecordCategory.name.desc(), Record.kind.desc(),
                  Record.uuid.desc()) \
        .all()
    return render_template('main/index.html', records=records)


@main.route('/by_days_spends')
def by_days_spends():
    return render_template('main/by_days_spends.html', day_sums=get_sums_by_days_spends())


@main.route('/by_months_spends')
def by_months_spends():
    return render_template('main/by_months_spends.html', month_sums=get_sums_by_months_spends())


@main.route('/by_categories')
def by_categories():
    return render_template('main/by_categories.html', years=get_years())


@main.route('/by_categories/<int:year>/<int:record_type_id>')
def by_categories_table(year, record_type_id):
    record_type = RecordType.query.get_or_404(record_type_id)
    categories = record_type.record_categories \
        .filter(RecordCategory.user_id == Config.records_user_id()) \
        .order_by(RecordCategory.name) \
        .all()
    return render_template('main/by_categories_table.html', year=year, record_type_id=record_type_id,
                           categories=categories, title='суммы по категориям. {} / {}'.format(year, record_type.name),
                           sums_by_categories_month=get_sums_by_categories_month(year, record_type_id))


@main.route('/current_month')
def current_month():
    d = datetime.date.today()
    d = d + relativedelta(months=1)
    d = d.replace(day=1)
    d = d + relativedelta(days=-1)
    total_days = d.day

    day = request.args.get('day', type=int)
    if day is not None and (day < 1 or day > total_days):
        abort(400)
    if day is None:
        day = datetime.date.today().day

    categories = []
    limits = {}
    spent = {}

    with open("month_limits.txt", 'r') as month_limits_file:
        for line in month_limits_file.readlines():
            split = line.split(" ")
            categories.append(split[0])
            limits[split[0]] = int(split[1])
            spent[split[0]] = 0

    start_date = datetime.date.today()
    start_date = start_date.replace(day=1)

    record_categories = db.session.query(RecordCategory.name, func.sum(Record.value)) \
        .filter(Record.record_category_uuid == RecordCategory.uuid, RecordCategory.user_id == Config.records_user_id(),
                Record.date >= start_date, RecordCategory.record_type_id == 1, Record.deleted == False) \
        .group_by(RecordCategory.name) \
        .all()

    for c in record_categories:
        spent[c[0]] = c[1]

    return render_template('main/current_month.html', total_days=total_days, day=day,
                           categories=categories, limits=limits, spent=spent)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}spend{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='photo_2018-10-14_16-07-16.jpg') }}">
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_jquery() }}
    {{ moment.include_moment() }}
    {{ moment.lang("ru") }}
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}" style="color: orangered">
                    spend
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.by_days_spends') }}">по дням</a></li>
                    <li><a href="{{ url_for('main.by_months_spends') }}">по месяцам</a></li>
                    <li><a href="{{ url_for('main.by_categories') }}">по категориям</a></li>
                    <li><a href="{{ url_for('main.current_month') }}">текущий месяц</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}

        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/error.html
{% extends 'base.html' %}

{% block page_content %}
    <h1>{{ message }}</h1>
{% endblock %}

app/templates/main/add_record.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% set title='новая запись' %}

{% block title %}{{ title }}{% endblock %}

{% block page_content %}

    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>

    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>

{% endblock %}

app/templates/main/by_categories.html
{% extends 'base.html' %}

{% set title='суммы по категориям' %}

{% block title %}{{ title }}{% endblock %}

{% block page_content %}

    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>

    <table class="table">
        <tr>
            <th>год</th>
            <th></th>
            <th></th>
        </tr>
        {% for year in years %}
            <tr>
                <td>{{ year }}</td>
                <td>
                    <a href="{{ url_for('main.by_categories_table',year=year,record_type_id=1) }}">
                        расходы
                    </a>
                </td>
                <td>
                    <a href="{{ url_for('main.by_categories_table',year=year,record_type_id=2) }}">
                        доходы
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

app/templates/main/by_categories_table.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block page_content %}

    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>

    <table class="table">
        <tr>
            <th>категория</th>
            {% for month in month_names %}
                <th>{{ month }}</th>
            {% endfor %}
            <th>всего</th>
        </tr>
        {% for category in categories %}
            <tr>
                <td><b>{{ category.name }}</b></td>
                {% for month in month_names %}
                    <td>{{ sums_by_categories_month.get(category.uuid, {}).get(loop.index) or '' }}</td>
                {% endfor %}
                <td><b>{{ sums_by_categories_month.get(category.uuid, {}).get(-1) or '' }}</b></td>
            </tr>
        {% endfor %}
        <tr>
            <td><b>всего</b></td>
            {% for month in month_names %}
                <td><b>{{ sums_by_categories_month.get('_all', {}).get(loop.index) or '' }}</b></td>
            {% endfor %}
            <td><b>{{ sums_by_categories_month.get('_all', {}).get(-1) or '' }}</b></td>
        </tr>

    </table>

{% endblock %}

app/templates/main/by_days_spends.html
{% extends 'base.html' %}

{% set title='сумма расходов по дням' %}

{% block title %}{{ title }}{% endblock %}

{% block page_content %}

    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>

    <table class="table">
        <tr>
            <th>дата</th>
            <th>сумма</th>
        </tr>
        {% for day_sum in day_sums %}
            <tr>
                <td>{{ day_sum.date }}</td>
                <td>{{ day_sum.sum }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

app/templates/main/by_months_spends.html
{% extends 'base.html' %}

{% set title='сумма расходов по месяцам' %}

{% block title %}{{ title }}{% endblock %}

{% block page_content %}

    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>

    <table class="table">
        <tr>
            <th>год</th>
            <th>месяц</th>
            <th>сумма</th>
        </tr>
        {% for month_sum in month_sums %}
            <tr>
                <td>{{ month_sum.year }}</td>
                <td>{{ month_names[month_sum.month - 1] }}</td>
                <td>{{ month_sum.sum }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

app/templates/main/current_month.html
{% extends 'base.html' %}

{% set title = 'текущий месяц' %}
{% set remain_days = total_days - day + 1 %}

{% block title %}{{ title }}{% endblock %}

{% block page_content %}

    <div class="page-header">
        <h1>{{ title }} (день {{ day }} из {{ total_days }})</h1>
    </div>

    <table class="table">
        <tr>
            <td></td>
            {% for category in categories %}
                <td>{{ category }}</td>
            {% endfor %}
            <th>сумма</th>
        </tr>
        <tr>
            <td>лимит</td>
            {% for category in categories %}
                <td>{{ limits[category] }}</td>
            {% endfor %}
            <th>{{ limits.values()|sum() }}</th>
        </tr>
        <tr>
            <td>потрачено</td>
            {% for category in categories %}
                <td>{{ spent[category] }}</td>
            {% endfor %}
            <th>{{ spent.values()|sum() }}</th>
        </tr>
        <tr>
            <td>осталось</td>
            {% for category in categories %}
                <td>{{ limits[category] - spent[category] }}</td>
            {% endfor %}
            <th>{{ limits.values()|sum() - spent.values()|sum() }}</th>
        </tr>
        <tr>
            <td>тратим в день</td>
            {% for category in categories %}
                <td>{{ "%.2f"|format(spent[category] / day) }}</td>
            {% endfor %}
            <th>{{ "%.2f"|format(spent.values()|sum() / day) }}</th>
        </tr>
        <tr>
            <td>осталось в день</td>
            {% for category in categories %}
                <td>{{ "%.2f"|format((limits[category] - spent[category]) / remain_days) }}</td>
            {% endfor %}
            <th>{{ "%.2f"|format((limits.values()|sum() - spent.values()|sum()) / remain_days) }}</th>
        </tr>
        <tr>
            <td>текущий баланс</td>
            {% for category in categories %}
                {% set balance = day / total_days * limits[category] - spent[category] %}
                <td>
                    {% if balance >= 0 %}
                        <span style="color: green;">{{ "%.2f"|format(balance) }}</span>
                    {% else %}
                        <span style="color: orangered;">{{ "%.2f"|format(balance) }}</span>
                    {% endif %}
                </td>
            {% endfor %}
            {% set total_balance = day / total_days * limits.values()|sum() - spent.values()|sum() %}
            <th>
                {% if total_balance >= 0 %}
                    <span style="color: green;">{{ "%.2f"|format(total_balance) }}</span>
                {% else %}
                    <span style="color: orangered;">{{ "%.2f"|format(total_balance) }}</span>
                {% endif %}
            </th>
        </tr>
    </table>

{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}

{% set title='spend' %}

{% block title %}{{ title }}{% endblock %}

{% block page_content %}

    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>

    {#    <a class="btn btn-success margined_button" href="{{ url_for('main.add_record') }}">новая запись</a>#}

    <table class="table">
        <tr>
            <th>тип</th>
            <th>дата</th>
            <th>время</th>
            <th>вид</th>
            <th>категория</th>
            <th>сумма</th>
        </tr>
        {% for record in records %}
            <tr>
                <td>
                    {% if record.record_category.record_type_id==1 %}
                        <span style="color:orangered;">расход</span>
                    {% elif record.record_category.record_type_id==2 %}
                        <span style="color:green;">доход</span>
                    {% endif %}
                </td>
                <td>{{ moment(record.date).format('LL')}}</td>
                <td>{{ record.time or '' }}</td>
                <td>{{ record.record_category.name }}</td>
                <td>{{ record.kind }}</td>
                <td>{{ record.value }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}